---
# Install the actual check scripts

- name: Install Metrics
  copy: src=roles/sensu_client/files/plugins/{{ item }} dest=/etc/sensu/plugins/{{ item }} mode=755
  with_items:
    - load-metrics.rb
    - disk-usage-metrics.rb
    - memory-metrics.rb

- name: Install Default Checks
  copy: src=roles/sensu_client/files/plugins/{{ item }} dest=/etc/sensu/plugins/{{ item }} mode=755
  with_items:
      - check-load.rb
      - check-mem.sh
      - check-smart.rb

- name: Restart Sensu Client Service
  service: name=sensu-client state=restarted
